version: '3'

services:
  costanza:
    image: costanza
    restart: unless-stopped
    environment:
      COSTANZA_DB_URL: postgres://costanza:myvoiceismypassportverifyme@db:5432/costanza
    build:
      context: .
      dockerfile: ./Dockerfile
    secrets:
      - source: costanza_config
        target: /etc/costanza/config.toml
    depends_on:
      db: 
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
  db:
    image: 'postgres:latest'
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: costanza
      POSTGRES_PASSWORD: myvoiceismypassportverifyme
      POSTGRES_DB: costanza
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "costanza"]
      interval: 10s
      timeout: 5s
      retries: 5
  migrate:
    image: 'migrate/migrate'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/database
    command:
      [ "-path", "/database", "-database", "postgres://costanza:myvoiceismypassportverifyme@db:5432/costanza?sslmode=disable", "up" ]

secrets:
  costanza_config:
      file: ./config.toml