version: '3'

services:
  costanza:
    restart: unless-stopped
    environment:
      COSTANZA_DB_URL: postgres://costanza:myvoiceismypassportverifyme@db:5432/costanza
      COSTANZA_METRICS_PORT: 8585
    build:
      context: .
      dockerfile: ./Dockerfile
    secrets:
      - source: costanza_config
        target: /etc/costanza/config.toml
    depends_on:
      db: 
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      register:
        condition: service_completed_successfully
    healthcheck:
      test: curl -f http://localhost:8585/api/v1/healthcheck || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
  cron:
    restart: unless-stopped
    environment:
      COSTANZA_DB_URL: postgres://costanza:myvoiceismypassportverifyme@db:5432/costanza
      COSTANZA_METRICS_PORT: 8585
    secrets:
      - source: costanza_config
        target: /etc/costanza/config.toml
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    command: ["/home/costanza/costanza", "cron"]
    healthcheck:
      test: curl -f http://localhost:8585/api/v1/healthcheck || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
  register:
    secrets:
      - source: costanza_config
        target: /etc/costanza/config.toml
    command:
      ["/home/costanza/costanza", "register"]

  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: costanza
      POSTGRES_PASSWORD: myvoiceismypassportverifyme
      POSTGRES_DB: costanza
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "costanza"]
      interval: 10s
      timeout: 5s
      retries: 5
  migrate:
    image: 'migrate/migrate'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/database
    command:
      [ "-path", "/database", "-database", "postgres://costanza:myvoiceismypassportverifyme@db:5432/costanza?sslmode=disable", "up" ]

secrets:
  costanza_config:
      file: ./config.toml
