[discord]
app_id = "app_id_here"
token = "example_token_here"
insomniac_ids = ["id1", "6789"]
insomniac_roles = ["role1", "9876"]
listen_configs = [
    {guild_id = "12345", report_channel_id = "67890", start_time = "16:00"},
    {guild_id = "54321", report_channel_id = "98760", start_time = "10:00"}
]
default_weather_locations = ["New York", "Paris"]

[metrics]
healthcheck_enabled = true
metrics_enabled = true
appname = "costanza-production"
log_level = "info"
port = 8585

[db]
connection = "postgres://user:password@localhost:5432/costanza"